---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Install the haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0755
  notify: Reload haproxy