---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy

- name: Ensure haproxy is started
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
