---
roles:
  - name: geerlingguy.nodejs
    version: 6.1.0
  - name: geerlingguy.postgresql
    version: 3.4.1
  - name: gantsign.golang
    version: 3.0.4
  - name: zorlin.rust
    version: 1.1.1
  - name: zorlin.pacemaker
  - name: zorlin.patroni
  - name: zorlin.etcd_cluster
