---
- name: Gather special node facts
  hosts: estuary
  become: true
  gather_facts: false

  tasks:
    - name: Gather all facts
      ansible.builtin.setup:

- name: Install base Estuary requirements
  hosts: estuary
  become: true

  roles:
    - estuary_system_user

  tasks:
    - name: Install prerequisites
      ansible.builtin.package:
        name: acl
        state: present

    - name: Grab info about the Estuary user
      ansible.builtin.user:
        name: "{{ estuary_system_user | default('estuary') }}"
        state: present
      register: estuary_system_user_info
      become: true

    - name: Add cargo env to bashrc
      ansible.builtin.lineinfile:
        path: "{{ estuary_system_user_info.home }}/.bashrc"
        line: '. "$HOME/.cargo/env"'
        state: present
        insertbefore: "# If not running interactively, don't do anything"
      become_user: "{{ estuary_system_user | default('estuary') }}"

    - name: Install build tools and compilers
      ansible.builtin.package:
        name: build-essential
        state: present

- name: Install Estuary API node(s)
  hosts: estuary_api
  become: true

  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      connection: local
      become: false
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: vault_password_file

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      connection: local
      become: false
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
      when: vault_password_file.stat.exists

    - name: Install prerequisites
      ansible.builtin.package:
        name: acl
        state: present

  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
      become_user: "{{ estuary_system_user | default('estuary') }}"
    - estuary_api

- name: Install Estuary shuttle nodes
  hosts: estuary_shuttle
  become: true

  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      connection: local
      become: false
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: vault_password_file

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      connection: local
      become: false
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
      when: vault_password_file.stat.exists

    - name: Install prerequisites
      ansible.builtin.package:
        name: acl
        state: present

  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
      become_user: "{{ estuary_system_user | default('estuary') }}"
    - estuary_shuttle

- name: Install Estuary web node
  hosts: estuary_www
  become: true

  roles:
    - geerlingguy.nodejs
    - estuary_www
