---
- name: Gather special node facts
  hosts: estuary
  become: true
  gather_facts: false

  tasks:
    - name: Gather all facts
      ansible.builtin.setup:

- name: Install base Estuary requirements
  hosts: estuary
  become: true

  tasks:
    - name: Install build tools and compilers
      ansible.builtin.package:
        name: build-essential
        state: present

- name: Install Estuary API node(s)
  hosts: estuary_api
  become: true

  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: vault_password_file

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
      when: vault_password_file.stat.exists

  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
      become_user: "{{ estuary_system_user | default('estuary') }}"
    - estuary_api

- name: Install Estuary shuttle nodes
  hosts: estuary_shuttle
  become: true
  remote_user: root

  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: vault_password_file

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
      when: vault_password_file.stat.exists

  roles:
    - estuary_system_user
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
      become_user: "{{ estuary_system_user | default('estuary') }}"
    - role: geerlingguy.postgresql
      become: true
      when: install_postgresql
    - estuary_shuttle

- name: Install Estuary web node
  hosts: estuary_www
  become: true

  roles:
    - geerlingguy.nodejs
    - estuary_www
