---
- name: Ensure /etc/ansible exists
  ansible.builtin.file:
    path: /etc/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure /etc/ansible/facts.d exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install UUID fact
  ansible.builtin.template:
    src: uuid.fact.j2
    dest: /etc/ansible/facts.d/uuid.fact
    owner: root
    group: root
    mode: 0400
