---
- name: Install main dependencies
  ansible.builtin.package:
    name:
      - wget
      - jq
      - hwloc
      - ocl-icd-opencl-dev
      - git
      - libhwloc-dev
      - pkg-config
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Create a system user for Estuary
  ansible.builtin.user:
    name: "{{ estuary_system_user | default('estuary') }}"
    shell: /bin/bash
    uid: 998
    system: true

- name: Check out Estuary from git
  ansible.builtin.git:
    repo: https://github.com/application-research/estuary
    dest: /usr/src/estuary
    version: v0.1.10

- name: Compile Estuary
  ansible.builtin.shell:
    # We force golang and cargo to load, otherwise Rust and Go won't work.
    cmd: . /etc/profile.d/golang.sh ; . "/root/.cargo/env" ; RUSTFLAGS="-C target-cpu=native -g" FFI_BUILD_FROM_SOURCE=1 make all
    creates: /usr/src/estuary/estuary
    chdir: /usr/src/estuary
    executable: /bin/bash

# Initialize main node
- name: Ensure estuary data directory
  ansible.builtin.file:
    path: /usr/src/estuary/data/
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0750
    state: directory
- name: Ensure estuary private directory
  ansible.builtin.file:
    path: /usr/estuary/private
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0700
    state: directory
    recurse: true
- name: Ensure estuary log directory
  ansible.builtin.file:
    path: /var/log/estuary/
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0750
    state: directory

- name: Get and store estuary token
  ansible.builtin.shell:
    cmd: /usr/src/estuary/estuary setup --database="{{ database_config }}" --username admin --password Password123 | grep Token | cut -d ' ' -f 3 > /usr/estuary/private/token
    creates: /usr/estuary/private/token
    executable: /bin/bash
    chdir: /usr/src/estuary/data/

# We save the estuary token we just generated in the playbook dir on the Ansible Controller host for now.
# This is not necessarily a super safe way to do it but works for demo purposes. Caveat emptor.
- name: Retrieve estuary token
  ansible.builtin.fetch:
    src: /usr/estuary/private/token
    dest: "{{ playbook_dir }}/secrets/token"
    flat: true

- name: Install estuary main service
  ansible.builtin.template:
    src: estuary.service
    dest: /etc/systemd/system/estuary.service
    owner: root
    group: root
    mode: 0755

- name: Create config directory for estuary
  ansible.builtin.file:
    path: /etc/estuary
    state: directory
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0755

- name: Copy main config
  ansible.builtin.template:
    src: config.env
    dest: /etc/estuary/config.env
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0640

- name: Copy logging config
  ansible.builtin.template:
    src: log.env
    dest: /etc/estuary/log.env
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0644

- name: Run daemon-reload
  command:
    cmd: systemctl daemon-reload

- name: Ensure estuary is running
  systemd:
    name: estuary
    state: started
    enabled: true
